use advent_of_code::*;
use std::error::Error;

fn main() -> Result<(), Box<dyn Error>> {
    run_advent_problem::<aoc_2022::regolith_reservoir::RegolithReservoir>()
}
